Revert relying on unity-hub error code, pipe stderr to null for unity-hub to remove error spam, improve error checking on windows image installs

diff --git a/images/ubuntu/editor/Dockerfile b/images/ubuntu/editor/Dockerfile
--- a/images/ubuntu/editor/Dockerfile
+++ b/images/ubuntu/editor/Dockerfile
@@ -10,7 +10,7 @@ FROM $hubImage AS builder
 # Install editor
 ARG version
 ARG changeSet
-RUN unity-hub install --version "$version" --changeset "$changeSet"
+RUN unity-hub install --version "$version" --changeset "$changeSet" | tee /var/log/install-editor.log && grep 'Failed to install\|Error while installing an editor\|Completed with errors' /var/log/install-editor.log | exit $(wc -l)
 
 # Install modules for that editor
 ARG module="non-existent-module"
@@ -18,7 +18,7 @@ RUN for mod in $module; do \
       if [ "$mod" = "base" ] ; then \
         echo "running default modules for this baseOs"; \
       else \
-        unity-hub install-modules --version "$version" --module "$mod" --childModules \
+        unity-hub install-modules --version "$version" --module "$mod" --childModules | tee /var/log/install-module-${mod}.log && grep 'Missing module\|Completed with errors' /var/log/install-module-${mod}.log | exit $(wc -l); \
       fi \
     done \
 	# Set execute permissions for modules
