editor: show output from unity-hub when installing unity and its modules
* fetching Unity takes very long, better show the progress during the fetch

diff --git a/editor/Dockerfile b/editor/Dockerfile
--- a/editor/Dockerfile
+++ b/editor/Dockerfile
@@ -10,14 +10,14 @@ FROM $hubImage AS builder
 # Install editor
 ARG version
 ARG changeSet
-RUN unity-hub install --version "$version" --changeset "$changeSet" | grep 'Error' | exit $(wc -l)
+RUN unity-hub install --version "$version" --changeset "$changeSet" | tee /var/log/install-editor.log && grep 'Error' /var/log/install-editor.log | exit $(wc -l)
 
 # Install modules for that editor
 ARG module="non-existent-module"
 RUN if [ "$module" = "base" ] ; then \
       echo "running default modules for this baseOs" ; exit 0 ; \
     else \
-      unity-hub install-modules --version "$version" --module "$module" --childModules | grep 'Missing module' | exit $(wc -l) ; \
+      unity-hub install-modules --version "$version" --module "$module" --childModules | tee /var/log/install-module-${module}.log && grep 'Missing module' /var/log/install-module-${module}.log | exit $(wc -l); \
     fi
 
 ###########################
@@ -45,19 +45,19 @@ RUN echo '#!/bin/bash' > /usr/bin/unity-editor \
 #=======================================================================================
 # [2019.3.[0-5]-linux-il2cpp] https://github.com/game-ci/docker/issues/76
 #=======================================================================================
-RUN [ `echo $version-$module | grep -v '^2019.3.[0-5]f.*-linux-il2cpp'` ] && exit 0 || : \
+RUN [ `echo "$version-$module" | grep -v '^2019.3.[0-5]f.*linux-il2cpp'` ] && exit 0 || : \
   && echo 'export IL2CPP_ADDITIONAL_ARGS=--tool-chain-path=/' >> /usr/bin/unity-editor
 
 #=======================================================================================
 # [2019.3.6+/2019.4.0-linux-il2cpp] https://forum.unity.com/threads/unity-2019-3-linux-il2cpp-player-can-only-be-built-with-linux-error.822210/#post-5633977
 #=======================================================================================
-RUN [ `echo $version-$module | grep -v '^\(2019.3.[6-9]f\|2019.3.1[0-9]f\|2019.4.0\).*-linux-il2cpp'` ] && exit 0 || : \
+RUN [ `echo "$version-$module" | grep -v '^\(2019.3.[6-9]f\|2019.3.1[0-9]f\|2019.4.0\).*linux-il2cpp'` ] && exit 0 || : \
   && echo 'export IL2CPP_ADDITIONAL_ARGS="--sysroot-path=/ --tool-chain-path=/"' >> /usr/bin/unity-editor
 
 #=======================================================================================
 # [2020.x/2020.2.0/2020.2.1-webgl] Support GZip compression: https://github.com/game-ci/docker/issues/75
 #=======================================================================================
-RUN [ `echo $version-$module | grep -v '^\(2020.1\|2020.2.0f\|2020.2.1f\).*-webgl'` ] && exit 0 || : \
+RUN [ `echo "$version-$module" | grep -v '^\(2020.1\|2020.2.0f\|2020.2.1f\).*-webgl'` ] && exit 0 || : \
   && echo 'export GZIP=-f' >> /usr/bin/unity-editor
 
 RUN echo 'xvfb-run -ae /dev/stdout "$UNITY_PATH/Editor/Unity" -batchmode "$@"' >> /usr/bin/unity-editor
@@ -70,7 +70,7 @@ RUN echo 'xvfb-run -ae /dev/stdout "$UNITY_PATH/Editor/Unity" -batchmode "$@"' >
 #=======================================================================================
 # [2018.x-android] Install 'Android SDK 26.1.1' and 'Android NDK 16.1.4479499'
 #=======================================================================================
-RUN [ `echo $version-$module | grep -v '^\(2018.3\|2018.4\).*-android'` ] && exit 0 || : \
+RUN [ `echo "$version-$module" | grep -v '^\(2018.3\|2018.4\).*android'` ] && exit 0 || : \
   \
   # Versions
   && export ANDROID_BUILD_TOOLS_VERSION=28.0.3 \
@@ -132,7 +132,7 @@ RUN [ `echo $version-$module | grep -v '^\(2018.3\|2018.4\).*-android'` ] && exi
 #=======================================================================================
 # [2019.x/2020.x/2021.x-android] Support usage of installed Android SDKs outside of editor
 #=======================================================================================
-RUN [ `echo $version-$module | grep -vP '^20(?!18).*-android'` ] && exit 0 || : \
+RUN [ `echo "$version-$module" | grep -vP '^20(?!18).*android'` ] && exit 0 || : \
   \
   # Install jq
   && apt-get update -qq \
@@ -185,7 +185,7 @@ RUN [ `echo $version-$module | grep -vP '^20(?!18).*-android'` ] && exit 0 || : 
 #=======================================================================================
 # [webgl] Support audio using ffmpeg (~99MB)
 #=======================================================================================
-RUN [ `echo $module | grep -v 'webgl'` ] && exit 0 || : \
+RUN [ `echo "$module" | grep -v 'webgl'` ] && exit 0 || : \
   && apt-get update \
   && apt-get -q install -y --no-install-recommends --allow-downgrades \
     ffmpeg \
@@ -195,7 +195,7 @@ RUN [ `echo $module | grep -v 'webgl'` ] && exit 0 || : \
 #=======================================================================================
 # [webgl, il2cpp] python python-setuptools build-essential clang
 #=======================================================================================
-RUN [ `echo $module | grep -v '\(webgl\|linux-il2cpp\)'` ] && exit 0 || : \
+RUN [ `echo "$module" | grep -v '\(webgl\|linux-il2cpp\)'` ] && exit 0 || : \
   && apt-get -q update \
   && apt-get -q install -y --no-install-recommends --allow-downgrades \
     python \
@@ -208,7 +208,7 @@ RUN [ `echo $module | grep -v '\(webgl\|linux-il2cpp\)'` ] && exit 0 || : \
 #=======================================================================================
 # [2019.x] libnotify4 libunwind-dev libssl1.0
 #=======================================================================================
-RUN [ `echo $version | grep -v '^2019.'` ] && exit 0 || : \
+RUN [ `echo "$version" | grep -v '^2019.'` ] && exit 0 || : \
   && apt-get -q update \
   && apt-get -q install -y --no-install-recommends --allow-downgrades \
     libnotify4 \
@@ -220,7 +220,7 @@ RUN [ `echo $version | grep -v '^2019.'` ] && exit 0 || : \
 #=======================================================================================
 # [2018.x/2019.x/2020.1.x-webgl] support brotli compression for linux
 #=======================================================================================
-RUN [ `echo $version-$module | grep -v '^\(2018\|2019\|2020.1\).*-webgl'` ] && exit 0 || : \
+RUN [ `echo "$version-$module" | grep -v '^\(2018\|2019\|2020.1\).*webgl'` ] && exit 0 || : \
   && cp \
     $UNITY_PATH/Editor/Data/PlaybackEngines/WebGLSupport/BuildTools/Brotli/dist/Brotli-0.4.0-py2.7-linux-x86_64.egg \
     $UNITY_PATH/Editor/Data/PlaybackEngines/WebGLSupport/BuildTools/Brotli/dist/Brotli-0.4.0-py2.7-macosx-10.10-x86_64.egg
@@ -228,7 +228,7 @@ RUN [ `echo $version-$module | grep -v '^\(2018\|2019\|2020.1\).*-webgl'` ] && e
 #=======================================================================================
 # [2021.x-linux-il2cpp] lld
 #=======================================================================================
-RUN [ `echo $version-$module | grep -v '^2021.*-linux-il2cpp'` ] && exit 0 || : \
+RUN [ `echo "$version-$module" | grep -v '^2021.*linux-il2cpp'` ] && exit 0 || : \
   && apt-get -q update \
   && apt-get -q install -y --no-install-recommends --allow-downgrades \
     lld \
